### ISSUE TITLE
Get unit tests passing on MicroPython

### ISSUE THREAD

**Issue by mjkillough** [mjkillough/feather-sonos#8]
... at least the Unix version.

Currently failing:

```
[feather] $ micropython test_discovery.py 
test_discover_actual_topology ...Traceback (most recent call last):
  File "test_discovery.py", line 146, in <module>
  File "/usr/lib/micropython/unittest.py", line 198, in main
  File "/usr/lib/micropython/unittest.py", line 153, in run
  File "/usr/lib/micropython/unittest.py", line 183, in run_class
  File "/usr/lib/micropython/unittest.py", line 178, in run_class
  File "test_discovery.py", line 113, in test_discover_actual_topology
  File "test_discovery.py", line 113, in test_discover_actual_topology
  File "test_discovery.py", line 110, in test_discover_actual_topology
AttributeError: 'ZoneGroupTopologyTests' object has no attribute 'assertCountEqual
```

**Comment by mjkillough** [comment]
They are now passing on the Unix version: fd76f760c88461e53a356ca2a5c2df1cd539ed57

**Comment by mjkillough** [comment]
ESP8266 version now works: f7701c9539aac3d4ac29d4ddd92482c55c986de4
